### ISSUE TITLE
Eaton Protection Station support

### ISSUE THREAD

**Issue by ygageot** [ToddGreenfield/homebridge-nut#6]
I have an Eaton Protection Station 650 and I want to integrate it in Homekit.
First to obtain a notification when power failure occurs and next to integrate the event in automatisation.
On a fresh raspberryPI2, I installed Jessie, a standalone default nut, home bridge and the plug in. 
The PI in powered by the Eaton and is also connected to it with USB cable.
I did the integration on iOs with Apple Home app but I tried also Eve app.
Everything was easy and seems to work; I disconnected the input power to understand more.

Running test.js, I discovered that **input.voltage** was not present (the main problem)
and also **battery.voltage**, **ups.temperature**  

the **ups.status** is only  **OL** during charging

I join a test.js output file after power reconnection.

[eaton.txt](https://github.com/ToddGreenfield/homebridge-nut/files/1303449/eaton.txt)

I have the impression it is better in place of **input.voltage** checking to see if **ups.status** starts with _OL_ or _OB_ to know if the power is obtained with the battery or not.

**Comment by ygageot** [comment]
I suggest for the **ContactServerState** to replace the test 
**upsInfo["input.voltage"] == "0.0"**
by 
**upsInfo["ups.status].startsWith("OB")**

because the ups.status seems to be always present.

**Comment by ToddGreenfield** [comment]
Hi - If you are comfortable making the changes and doing a PR, feel free. Otherwise I will try and take a look at this over the weekend.

**Comment by ygageot** [comment]
I made some local mods about ContactState and it works for me.
I replace the values true/false by official integer constant and now triggers works and I have notifications on my iPhone.

I tried to send a **Pull Request** but I have an **Authentification Failed**

Is there a trick of permissions ?

**Comment by ToddGreenfield** [comment]
@ygageot I just pushed 1.0.8 which makes the changes you suggested - thank you. I also replaced the boolean true/false with 1/0 as well as moved the voltage/temp readings so they would update appropriately as they were only reading the originally pulled values for some reason (prior PR I believe). Give this a try and let me know how it works for you. I tested and it works well for me.
