### ISSUE TITLE
Voltage, Freq from UPS

### ISSUE THREAD

**Issue by sledzik1984** [ToddGreenfield/homebridge-nut#8]
Plugin should show parameters from UPS like input voltage, input frequency... all needed data is available through NUT

**Comment by ToddGreenfield** [comment]
It should show those parameters. Try using the EVE app instead of appleHome.

**Comment by ToddGreenfield** [comment]
Feel free to do a PR for anything not currently showing. Eve will show the following-
<img src="https://user-images.githubusercontent.com/24653339/35187013-56b8b5e0-fdeb-11e7-8cb3-953315af303c.jpg" width="200" />
