### ISSUE TITLE
Error: This callback function has already been called by someone else; it can only be called one time.

### ISSUE THREAD

**Issue by abpostelnicu** [ToddGreenfield/homebridge-nut#9]
Hello,

As homebridge boots I get:

[2018-2-23 10:50:13] [SERVER_UPS] Received Nut accessory ROUTER_UPS (Server UPS) from the SERVER_UPS platform.
[2018-2-23 10:50:13] [SERVER_UPS] Received Nut accessory SERVER_UPS (SERVER UPS) from the SERVER_UPS platform.
[2018-2-23 10:50:13] [SERVER_UPS] Nut Error: ERROR getting UPSVars: Other communication still running

......

[2018-2-23 10:50:52] Homebridge is running on port 51826.

/homebridge/node_modules/node-nut/node-nut.js:74
                        callback(vars, null);
   ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at /homebridge/node_modules/homebridge-nut/index.js:66:7
    at /homebridge/node_modules/homebridge-nut/index.js:112:6
    at /homebridge/node_modules/node-nut/node-nut.js:99:4
    at parseKeyValueList (/homebridge/node_modules/node-nut/node-nut.js:74:4)
    at Nut.parseFunc (/homebridge/node_modules/node-nut/node-nut.js:97:3)
    at Socket.<anonymous> (/homebridge/node_modules/node-nut/node-nut.js:33:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)

My 2 UPS are working perfectly with other monitoring tools that are based on upsc.

**Comment by ToddGreenfield** [comment]
Can you run the command-
echo "LIST UPS" | nc localhost 3493

**Comment by abpostelnicu** [comment]
Sure:

BEGIN LIST UPS
UPS ROUTER_UPS "Server UPS"
UPS SERVER_UPS "SERVER UPS"
END LIST UPS

**Comment by ToddGreenfield** [comment]
I believe the problem is because the ups.conf description "what's in quotes" is the same name (one is just capitalized). That is what is used to populate the accessory name in homebridge. I suggest changing the first one to "Router Ups" to match its actual name. Then restart the nut services or just reboot. Let me know if that works-

**Comment by abpostelnicu** [comment]
unfortunately the problem still persists:

echo "LIST UPS" | nc localhost 3493
BEGIN LIST UPS
UPS ROUTER_UPS "ROUTER UPS"
UPS SERVER_UPS "SERVER UPS"
END LIST UPS

**Comment by ToddGreenfield** [comment]
ok, apparently nobody else has used this (successfully) with multiple UPS's including me. I setup a dummy-ups and was able to recreate the issue. Will work on fixing-

**Comment by abpostelnicu** [comment]
Great this is awesome. Let me know if I can help!

**Comment by ToddGreenfield** [comment]
Resolved. Please update and try now. This took a bit to figure out as there were timing/communication issues giving me grief.
